import { drizzleZeroConfig } from "drizzle-zero";
import * as drizzleSchema from "~/db/schema";

export default drizzleZeroConfig(drizzleSchema, {
	tables: {
		verification: false,
		account: false,
		session: false,
		jwks: false,
		user: {
			id: true,
			name: true,
			email: true,
			image: true,
			emailVerified: true,
			createdAt: true,
			updatedAt: true,
		},
		invitation: false,

		// Organization and members
		organization: {
			id: true,
			slug: true,
			name: true,
			logo: true,
			metadata: true,
			createdAt: true,
		},
		member: {
			id: true,
			organizationId: true,
			userId: true,
			role: true,
			createdAt: true,
		},
		carrier: {
			id: true,
			organizationId: true,
			name: true,
			apiKey: true,
			createdAt: true,
			updatedAt: true,
		},
		carrierService: {
			id: true,
			carrierId: true,
			name: true,
			code: true,
			createdAt: true,
			updatedAt: true,
		},
		dutyTaxCalculation: {
			id: true,
			organizationId: true,
			calculationDetails: true,
			countryCode: true,
			dutyAmount: true,
			taxAmount: true,
			orderId: true,
			name: true,
			code: true,
			createdAt: true,
			updatedAt: true,
		},
		order: {
			id: true,
			storeId: true,
			customerId: true,
			orderNumber: true,
			status: true,
			totalAmount: true,
			shippingAddress: true,
			billingAddress: true,
			createdAt: true,
			updatedAt: true,
		},
		orderItem: {
			id: true,
			orderId: true,
			productId: true,
			quantity: true,
			unitPrice: true,
			subtotal: true,
			createdAt: true,
			updatedAt: true,
		},
		product: {
			id: true,
			storeId: true,
			name: true,
			sku: true,
			price: true,
			weight: true,
			dimensions: true,
			hsCode: true,
			createdAt: true,
			updatedAt: true,
		},
		shipment: {
			id: true,
			orderId: true,
			carrierId: true,
			carrierServiceId: true,
			trackingNumber: true,
			labelUrl: true,
			rate: true,
			createdAt: true,
			updatedAt: true,
		},
		shippingRate: {
			id: true,
			orderId: true,
			carrierId: true,
			carrierServiceId: true,
			estimatedDelivery: true,
			rate: true,
			createdAt: true,
			updatedAt: true,
		},
		store: {
			id: true,
			organizationId: true,
			name: true,
			platform: true,
			apiKey: true,
			apiSecret: true,
			storeUrl: true,
			createdAt: true,
			updatedAt: true,
		},
	},
});
